### PR TITLE
Add Kong's participation

### PR DESCRIPTION
**Pull request by jonyeezs**

### CODE REVIEW

**Comment by crweiner** [comment]
Hay @jonyeezs! You're awesome, thanks for adding to the list! :smile: 

Would you mind just adjusting your links to the Kong code/repo and documentation to follow [GitHub Flavored Markdown](https://github.github.com/gfm/)? This link here would be a great reference to see what I mean: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

I'll make a few suggestions soon so you can see what I mean. When you go ahead and make those changes, just commit the files to your same ```master``` branch and let me know!

**Comment by jonyeezs** [comment]
Hi, sorry forgot a spacing in there. Should be fine now :ok_hand:

**Comment by crweiner** [comment]
Thanks for that edit, @jonyeezs 

Can you please work on the links to the forum post, repo, docs, etc? I mentioned that in my code review above. Please be sure to format your links like this:
```
See a link to the post [here](https://www.example.com)
```
With the clickable text surrounded in ```[]``` and the actual URL immediately follows in ```()```

Once you have the links formatted correctly, and double check that all of the things I [pointed out here](https://github.com/crweiner/hacktoberfest-swag-list/pull/5/files) are fixed, I'd love to get Kong on the list! Thanks again and please let me know if you have any questions! :smile:

**Comment by jonyeezs** [comment]
Actually the format given is valid github markdown.

It's easier to read the raw file this way with reference (given it being a
very long line).

But yes i can change that 👌

**Comment by crweiner** [comment]
Yep, you're absolutely right, I'm sorry about that. For simplicity sake, good `ole fashioned links make it easier for new people to add to this list by copying and pasting a prior item then just changing the URL. At least that's my opinion anyway...this little Markdown list doesn't have very high expectations. :wink:

**Comment by jonyeezs** [comment]
PR changes as commented

**Comment by crweiner** [comment]
You rock @jonyeezs! Thanks again! :boom:

**Pull request merged**
