### PR TITLE
docs: Adds entry for Appsmith

### PR DESCRIPTION
**Pull request by cokoghenun**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hey there @cokoghenun!! 👋 Thank you so much for contributing to the Hacktoberfest Swag List! 👍 

I'd love to get Appsmith on the list and there's few things I'd love for you to add based on [the Contributing guidelines](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md). Could you please add a link to Appsmith's swag signup page, and break things down a little bit more in the _Least Involvement To Most Involvement_ section?

The [2020 branch](https://github.com/crweiner/hacktoberfest-swag-list/tree/2020) is full of lots of companies that gave out swag at different contribution levels, so please model Appsmith's entry off of that (they were on the list last year too!).

Thanks and hope you'll have a great Hacktoberfest! 😄

**Comment by cokoghenun** [comment]
Thanks @crweiner I'll do that

**Comment by crweiner** [comment]
Thanks for the updates, @cokoghenun! Because Appsmith has different tiers of swag, can you please also add them to the **2 or more Merged PRs** and **5 or more Merged PRs** sections?

**Comment by cokoghenun** [comment]
Thanks for the feedback @crweiner. I've made the changes, please take a look.

**Comment by crweiner** [comment]
Woohoo!! 🎉 Thank you so much @cokoghenun for taking care of those changes! I appreciate your hard work and thank you for getting Appsmith on the Swag List! 👍 😄 

You rock! Have a wonderful Hacktoberfest!

awesome job

**Comment by cokoghenun** [comment]
Thanks 😄

**Pull request merged**
