### PR TITLE
Add Chainguard to Hacktoberfest Swag List

### LINKED ISSUE #846: Add Chainguard to Hacktoberfest Swag List
[Chainguard](https://dev.to/chainguard/get-involved-with-chainguard-projects-for-hacktoberfest-2023-4h7b) is  participating  in Hacktoberfest 2023!

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

### PR DESCRIPTION
**Pull request by shubhusion**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request(Fixes #846), please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @shubhusion! It looks like the Chainguard team has [three different ways to contribute during Hacktoberfest](https://dev.to/chainguard/get-involved-with-chainguard-projects-for-hacktoberfest-2023-4h7b). I know that the holiday is almost over, but if you could please update your PR to cover some additional details, I'll review it quickly! Just tag me when you're ready, thanks!

**Comment by shubhusion** [comment]
@crweiner I have made the changes.

**Comment by crweiner** [comment]
Hi @shubhusion, thank you for your updates. I took a look a the [deploy preview](https://deploy-preview-853--hacktoberfest-swag-list.netlify.app/list), and the spacing does not look correct:

Markup on 2023-10-31 at 22:45:48

Thank you for adding the additional information, I'll work on making MkDocs happy. 😃

**Comment by crweiner** [comment]
Alrighty, fixed it! That looks better now! Thank you again for your PR @shubhusion, and I hope you had a great Hacktoberfest!

**Pull request merged**
