### PR TITLE
Added DX Heroes

### PR DESCRIPTION
**Pull request by DominikMilaniak**
I've added DX Heroes to this awesome list.

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @DominikMilaniak!! Thank you so much for adding DX Heroes to the Hacktoberfest Swag List! :tada: You made my day by calling this little project awesome. :smile:

I made a few small changes that I'd love for you to verify. To make sure that people fill out the correct forms and not fall victim to scammers, I always make sure to grab the form details from an official post. I saw that you made the [commit on DX Scanner](https://github.com/DXHeroes/dx-scanner/commit/f11dcf63bc0956893e6c0b0def7d563bb21c7a2c) to add the Google Form and Hacktoberfest info, so I grabed the form URL from that post.

Please let me know if I've got the correct Google Form here now. If it is, then I'll get this merged ASAP! :smile:

**Comment by scorpion-kali** [comment]
Can, I do pull request for your repo

**Comment by DominikMilaniak** [comment]
Yes, that is in fact the correct form URL :) Thank you for grabbing the right URL, you are awesome! :)

**Comment by DominikMilaniak** [comment]
@scorpion-kali If your comment was addressed to me, then yes, it would be awesome! All though I encourage you to wait 1 more day to be eligible for rewards as a part of the Hacktoberfest 2020 event (more here: https://linktr.ee/dxheroes). 

If you comment wasn't for me, then don't mind me 😄

**Comment by scorpion-kali** [comment]
@DominikMilaniak sure

**Comment by crweiner** [comment]
Thanks for the confirmation @DominikMilaniak! 👍😊 Let's get this puppy live! 🎉🎉

And @scorpion-kali, all sorts of projects are preparing for Hacktoberfest so go out and make meaningful, helpful contributions to those projects you love. ❤️❤️

**Pull request merged**
