### PR TITLE
Adding Earthly

### PR DESCRIPTION
**Pull request by agbell**
Adding earthly, as mentioned here https://blog.earthly.dev/hacktoberfest-2020/

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

 @crweiner

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @agbell! Thank you so much for adding Earthly to the Hacktoberfest Swag List! I'd love to get this merged ASAP so we can tell more people about your project and send some meaningful PRs your way! 🎉 

Just a few things to clarify; can you please add that this is limited to the first 40 participants and that they have to email adam@earthly.dev? I want to make sure that all those who rightfully earn a Earthly sticker can get one. 😄 Thank you!

**Comment by agbell** [comment]
@crweiner Addressed!

**Comment by crweiner** [comment]
Thank you so much @agbell! You rock! I hope we can send some great PRs your way and have a great Hacktoberfest! 🎉 

high five

**Comment by agbell** [comment]
Woohoo - thank you @crweiner

**Pull request merged**
