### PR TITLE
add steps for building site locally

### PR DESCRIPTION
**Pull request by Asmit2952**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hello @Asmit2952! Thank you very much for taking the time to write this out! I hope that this project has helped you grow and learn something new during Hacktoberfest! 

You did _exactly_ the right thing: you found a project that you found interesting, you wanted to help, you then learned how to help, taught yourself something new, and then turned around and wanted to share your knowledge to help others. ❤️ I'm very appreciative of this PR because I know first-hand the type of work that goes into learning how to setup a local environment for the first time.

clapping

Thank you again for your PR, and I hope you continue to have a wonderful Hacktoberfest! 👍 🎉

**Comment by crweiner** [comment]
If you are up for another challenge, @Asmit2952, this site can also run in Docker, but the build file needs to be adjusted first to add the dependencies for your other great contribution in #575 and the plugin I've included in #659. 

If you're up for writing that guide for the Contributing.md file, I'm up for it too! I've been playing around with getting Docker working in the [docker branch](https://github.com/crweiner/hacktoberfest-swag-list/tree/docker), if you want to see me break things live. 😅

**Comment by Asmit2952** [comment]
> Hello @Asmit2952! Thank you very much for taking the time to write this out! I hope that this project has helped you grow and learn something new during Hacktoberfest! 
> 
> You did _exactly_ the right thing: you found a project that you found interesting, you wanted to help, you then learned how to help, taught yourself something new, and then turned around and wanted to share your knowledge to help others. ❤️ I'm very appreciative of this PR because I know first-hand the type of work that goes into learning how to setup a local environment for the first time.
> 
> clapping
> 
> Thank you again for your PR, and I hope you continue to have a wonderful Hacktoberfest! 👍 🎉 

Thank you @crweiner, you are too kind 😄. This project did help me learn about something new that I had never used before. Thank you for this opportunity and I hope we continue collaborating on different projects as well 😁.

**Comment by Asmit2952** [comment]
> If you are up for another challenge, @Asmit2952, this site can also run in Docker, but the build file needs to be adjusted first to add the dependencies for your other great contribution in #575 and the plugin I've included in #659. 
> 
> If you're up for writing that guide for the Contributing.md file, I'm up for it too! I've been playing around with getting Docker working in the [docker branch](https://github.com/crweiner/hacktoberfest-swag-list/tree/docker), if you want to see me break things live. 😅 

I'm up for it 🚀

**Pull request merged**
