### PR TITLE
Adding Milvus as company

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
#402 

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hey @mohitsaxenaknoldus! 👋 Thanks for your PR to the Hacktoberfest Swag List! Would you be able to tackle the[ md flags from Code Climate](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/408)? I setup that robotic overlord to make sure that the markdown -> HTML gets rendered properly and consistently for the site. 🤖

Thank you!

**Comment by mohitsaxenaknoldus** [comment]
> Hey @mohitsaxenaknoldus! wave Thanks for your PR to the Hacktoberfest Swag List! Would you be able to tackle the[ md flags from Code Climate](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/408)? I setup that robotic overlord to make sure that the markdown -> HTML gets rendered properly and consistently for the site. robot
> 
> Thank you!

Done! Thank you!

**Comment by crweiner** [comment]
Hey @mohitsaxenaknoldus! Thanks for that! Sorry I missed this earlier, but can you please add Milvus in the _Least Involvement to Most Involvement_ section of the List too? That section has slightly different formatting rules, so please [follow the Contributing Guidelines](https://hacktoberfestswaglist.com/contributing) closely. 👍 Thank you!!

**Comment by mohitsaxenaknoldus** [comment]
> Hey @mohitsaxenaknoldus! Thanks for that! Sorry I missed this earlier, but can you please add Milvus in the _Least Involvement to Most Involvement_ section of the List too? That section has slightly different formatting rules, so please [follow the Contributing Guidelines](https://hacktoberfestswaglist.com/contributing) closely. +1 Thank you!!

Sure! I'll update right away!

**Comment by mohitsaxenaknoldus** [comment]
Hey @crweiner please check now.

**Comment by crweiner** [comment]
Thank you again @mohitsaxenaknoldus for another addition to the Hacktoberfest Swag List! 🎉 🎉 🎉 I appreciate your contributions and hope you have a wonderful Hacktoberfest! 🎃 🍂 

great job

**Pull request merged**
