### PR TITLE
Add CircleCI

### PR DESCRIPTION
**Pull request by swapniljha001**
Added CircleCI Hacktoberfest details.

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly.
2. [x] I'm not adding a company from the blocklist.
3. [x] I make sure to fix things promptly if an error or suggestion comes up.

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by swapniljha001** [comment]
My mistake, I didn't see that an issue regarding the addition of CircleCI to this list has already been raised (#257) and people have already contributed to that. I just came across this list and added the one organization which I thought was missing.

**Comment by crweiner** [comment]
Hi there @swapniljha001! 👋 No worries at all! I value genuine contributions to the Swag List and appreciate your time to make this List even better. I haven't chosen one to merge yet so you may still be the lucky winner. 😉

**Comment by crweiner** [comment]
Hey @swapniljha001! 👋  Thank you for your hard work adding CircleCI to the Hacktoberfest Swag List! 👍 

I had multiple PRs to add CircleCI, so I can't merge them all. I appreciate your time and effort working on this PR, but sadly I'll have to close it. Don't worry, this will still count towards Hacktoberfest because you did submit a real PR that followed the [Hacktoberfest standards](https://hacktoberfest.digitalocean.com/details#quality) 😄 

Thank you again, I hope you understand, and have a great Hacktoberfest!

**Comment by swapniljha001** [comment]
Thanks for the kind words @crweiner :)

**Pull request closed without merging**
