### PR TITLE
Feature/rearrange swag list

### PR DESCRIPTION
**Pull request by adriennetacke**
Hi there! I took a stab at rearranging the swag list as requested in issue #16 and added two sort orders:

- A- Z list of Companies
- Least Involvement to Most Involvement

I also added some quick jump links to these lists.

### CODE REVIEW

**Comment by crweiner** [comment]
WOW @adriennetacke!!! I love it! You've tackled Issue #16 in a **BIG** way and I think this is a wonderful way to reorganize the list. :smile: It's also making me want to turn this into a website, rather than just a simple Markdown list :thinking: .

Would you be able to update your branch to also include the latest additions to the list, Magento and LBRY? 

Also, if you have the time to update [How to format your contribution](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md#how-to-format-your-contribution) now that the structure of the list has changed to include the companies in multiple places, that would be incredible. 

Feel free to make the updates to `CONTRIBUTING.md` in  [How to format your contribution](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md#how-to-format-your-contribution) its own separate PR. That alone might be a lot of work and warrant it's own PR to count towards Hacktoberfest. :+1: Beleive me, I know how important it is to earn your swag! :wink: 

Let me know your thoughts. Because this is a big change in how the list is organized, I just would love to have clearer rules for future contributors.

And thank you again! This is great work! :1st_place_medal:

**Comment by adriennetacke** [comment]
@crweiner Thank you! :) 

I have no problem adding them to the list. I'll do that soon. 

And yes, since you mentioned it, I'll totally take up your offer on submitting the contribution changes in a separate PR ;) 

Thanks again! :)

**Comment by adriennetacke** [comment]
Ok, it's good to go. Added Magento and LBRY as requested. 😄

**Comment by crweiner** [comment]
Thank you so much for making those changes! I'll have a look at the Code Climate suggestions this weekend and make any tweaks, if needed. I had to add that because some other people clearly didn't know markdown and were just guessing in their PRs... GitHub does a good job at rendering markdown so I'm sure most of the flags aren't actually real issues we'll run into. 

You rock for doing this to help the community earn more Hacktoberfest swag! :boom:

**Comment by crweiner** [comment]
Thank you again for all of your help in reorganizing the list! 

I am still working on the Code Climate flags, but I wanted to get this merged so people can start taking advantage of it. 

You're incredible! :boom:

**Comment by adriennetacke** [comment]
Whoo! Thank you! 😄

**Pull request merged**
