### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ramadh-xic**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
As I explained to you in #334, spam for the sake of trying to get a shirt from Hacktoberfest isn't allowed. Hacktoberfest is implementing a [banning system very soon](https://github.com/devoverid/hacktoberfest) and it's actions like this that get you banned from the event for life.
👎 

I have reviewed and flagged every repo you have submitted PRs to as being spam and invalid for Hacktoberfest. Way to go.

**Comment by ramadh-xic** [comment]
Im sorry, why did you reject my PR?

Pada tanggal Sen, 5 Okt 2020 pukul 11.31 Chandler Weiner <
notifications@github.com> menulis:

**Comment by crweiner** [comment]
> Im sorry, why did you reject my PR? 

Hi @ramadh-xic, this is what I posted in #334 and is why this PR is marked as spam:


> I've looked at PRs you have submitted at other repos [here](https://github.com/OpenSouceCode/Hacktoberfest2020/pull/1378), [here](https://github.com/rui314/chibicc/pull/14), [here](https://github.com/creative-computing-society/Hacktoberfest2020_CCS/pull/174), [here](https://github.com/nightcore420/hacktosgbteam/pull/30), etc as well as an Issue that you posted for #338. It appears as if you are trying to cheat and submit low-quality PRs for Hacktoberfest.
> 
> Do you really think that a shirt is worth this? With the [new Hacktoberfest rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update), you can be banned from earning any swag as a result of these actions.
> 
> Please make meaningful PRs to projects you love, not send spam to maintainers such as myself. 👎

**Comment by ramadh-xic** [comment]
I'm sorry im new in Hacktoberfest, sorry bro,

Pada tanggal Sel, 6 Okt 2020 pukul 09.40 Chandler Weiner <
notifications@github.com> menulis:

**Pull request closed without merging**
