### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tylerwolf35**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hello @tylerwolf35! 👋 Thank you for your PR, and for finding that typo!

It looks like you may have an old fork of this repo because of the old [index.md file here](https://github.com/crweiner/hacktoberfest-swag-list/pull/599/files#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5). Can you please perform a `git rebase` or delete your fork, re-fork this repo, and make your correction there?

Please ping me either here or in a new PR when you'd like me to take a look! 👀 Thanks again, and happy Hacktoberfest!

**Comment by crweiner** [comment]
> the index.md file seems to be up-to-date, the only diff being the changes i made due to the typo, i can always re-fork if necessary, but git rebase isn't going to do anything

Ahhh, you caught something I overlooked!

You can see in your [file here](https://github.com/crweiner/hacktoberfest-swag-list/pull/599/files#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5R959) that it references the 2021 entry for Bagisto. The index.md file is now being generated from [/docs/index.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/index.md) and is no longer pulling from the root of the repo. I'll go ahead and delete that old index.md file now, thanks for making me aware that it was still there!

What you have there is a snapshot in time for when I was testing converting this site from Jekyll to MkDocs and used the old list as a test. 🧪 

If you could please remove it from your fork as well, that would be great so we don't add it back accidentally. 😅

**Comment by tylerwolf35** [comment]
> > the index.md file seems to be up-to-date, the only diff being the changes i made due to the typo, i can always re-fork if necessary, but git rebase isn't going to do anything
> 
> Ahhh, you caught something I overlooked!
> 
> You can see in your [file here](https://github.com/crweiner/hacktoberfest-swag-list/pull/599/files#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5R959) that it references the 2021 entry for Bagisto. The index.md file is now being generated from [/docs/index.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/index.md) and is no longer pulling from the root of the repo. I'll go ahead and delete that old index.md file now, thanks for making me aware that it was still there!
> 
> What you have there is a snapshot in time for when I was testing converting this site from Jekyll to MkDocs and used the old list as a test. test_tube
> 
> If you could please remove it from your fork as well, that would be great so we don't add it back accidentally. sweat_smile

alright, i've done that

**Comment by crweiner** [comment]
Awesome, thank you @tylerwolf35. Have a great Hacktoberfest!

thank you

**Pull request merged**
