### PR TITLE
mistyped repositories

### PR DESCRIPTION
**Pull request by biplobsd**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Aahhhh, thank you @biplobsd, I didn't catch that. I've never been good at spelling 😆 Appreciate it!

**Comment by biplobsd** [comment]
> Aahhhh, thank you @biplobsd, I didn't catch that. I've never been good at spelling 😆 Appreciate it!

@crweiner 
Also me. I just copied paste all in google docs, then google docs showing me red underline this word.. 😁😃

Thanks for doing amazing work. It is reducing our time for searching challenges individually.

clapping-leonardo-dicaprio

**Comment by crweiner** [comment]
You're too kind. 😄 Just doing my little part to make Hacktoberfest even better by connecting people who want to help with projects that could use a hand.

aww shucks

**Comment by biplobsd** [comment]
Hey

> You're too kind. 😄 Just doing my little part to make Hacktoberfest even better by connecting people who want to help with projects that could use a hand.
> 
> aww shucks

@crweiner, maybe you forgot to add label on this PR...

**Pull request merged**
