### PR TITLE
Adding Globo.com to Hacktoberfest swag list

### PR DESCRIPTION
**Pull request by DevIvanVarela**

### CODE REVIEW

**Comment by crweiner** [comment]
Hay there @DevIvanVarela! Thanks for letting us know of a new swag opportunity! I'm looking forward to getting this live once we can clarify a few things:

1. Please add something in the **Notes** section regarding an official blog post, tweet, or something showing that their participation is legitimate. 
2. Please add them in the **Least Involvement to Most Involvement** section of the `Readme.md`.
3. Please remove the bit.ly link and replace with the full URL of where people need to go.
4. Double check that everything meets the guidelines set in [the Contributing page](https://hacktoberfestswaglist.com/contributing) and let me know when you'd like me to take a look at this PR again.

Thank you again for your time and contribution!!

**Comment by DevIvanVarela** [comment]
Hello @crweiner! Thank you for the review!

I'll do the changes today, and submit a new commit with the corrections.

**Comment by pedrophs** [comment]
Maybe should be noted that the t-shirt will be delivered only to Brazilian territory.

https://opensource.globo.com/hacktoberfest/

> Os 200 primeiros inscritos ganharão uma
camiseta exclusiva a ser entregue dentro
do território brasileiro.

> The first 200 registrants will win a
exclusive t-shirt to be delivered in
of Brazilian territory.

**Comment by crweiner** [comment]
> Maybe should be noted that the t-shirt will be delivered only to Brazilian territory.
> 
> https://opensource.globo.com/hacktoberfest/

Aah yes, that is important to note. @DevIvanVarela, could you add this please under the **Notes** section?

**Comment by crweiner** [comment]
Added in #134 and anyone is welcome to update the list if Globo.com needs to be clarified! :smile:

**Pull request closed without merging**
