### PR TITLE
Add Operation Code to Swag list

### PR DESCRIPTION
**Pull request by PatrickRNG**

### CODE REVIEW

**Comment by crweiner** [comment]
Hay @PatrickRNG!! You rock! Thanks for adding Operation Code to the swag list! I appreciate you taking the time to read our Contributing documents and do a great job formatting things properly. If you could please just take a look at the issues flagged by CodeClimate and try to fix as many of those small things as you can, I'd greatly appreciate it (it helps to make sure that the list renders properly in Jekyll each time). Then we can get this merged right away!! :+1:

**Comment by crweiner** [comment]
Thanks for making the changes! There's one last thing I just noticed (and I'm sorry if I missed this before). Can you please alphabetize Operation Code in the **2 or more Merged PRs** section? It's currently the first on the list there instead of after Accord Project. Thank you again!!

**Comment by PatrickRNG** [comment]
Sure! Done, sorry for that

**Comment by crweiner** [comment]
You rock @PatrickRNG!!! Thank you so much! Let's get this merged and live and thank you for your contributions to the Hacktoberfest Swag List!

thumbs up

**Pull request merged**
