### PR TITLE
Updated Gemfile, _layout file

### PR DESCRIPTION
**Pull request by codewithdev**
gem package added "tzinfo-data"
_default.html added "scroll to top"

### CODE REVIEW

**Comment by crweiner** [comment]
I would be interested in adding a scroll to the top hovering button if that's something you'd like to contribute.

**Comment by codewithdev** [comment]
> I would be interested in adding a scroll to the top hovering button if that's something you'd like to contribute.

Yes

**Comment by crweiner** [comment]
Looking forward to it! Obviously, that'll be without all of this Gemfile, Product Hunt, and .gitignore editing... :+1:

**Comment by crweiner** [comment]
If you want to make a contribution, please delete your current fork, refork the project, and set up individual branches right away for the changes you wish to make. This is quite out of hand.

**Pull request closed without merging**
