### PR TITLE
[WIP]Fix CSS for footer on smaller screens

### LINKED ISSUE #93: Css is broken on the site
[Here](https://user-images.githubusercontent.com/8070553/66002199-d1170c80-e4ab-11e9-80b3-846b2635527a.png) is a screenshot

Browser: Chrome 77.0.3865.90
OS: MacOS

### PR DESCRIPTION
**Pull request by dehrax**
Fixes #93

### CODE REVIEW

**Comment by dehrax** [comment]
@crweiner Any error message from Netlify?

**Comment by crweiner** [comment]
Hay @dehrax! Thanks for taking the time to try and fix this for me! 

Unfortunately, Netlify threw an error. Here's the relevant portion of the log:

```bash
12:55:56 PM: Executing user command: jekyll build --drafts
12:55:57 PM: Configuration file: /opt/build/repo/_config.yml
12:55:58 PM:             Source: /opt/build/repo
12:55:58 PM:        Destination: /opt/build/repo/_site
12:55:58 PM:  Incremental build: disabled. Enable with --incremental
12:55:58 PM:       Generating...
12:55:58 PM: Invalid theme folder: _sass
12:55:58 PM:       Remote Theme: Using theme pages-themes/minimal
12:55:58 PM: Invalid theme folder: _includes
12:55:58 PM:        Jekyll Feed: Generating feed for posts
12:55:58 PM:   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
12:55:58 PM:                     File to import not found or unreadable: minimal. Load paths: /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-theme-primer-0.5.3/_sass /tmp/jekyll-remote-theme-20191003-1412-1p2nodz/_sass on line 1
12:55:58 PM: jekyll 3.8.5 | Error:  File to import not found or unreadable: minimal.
12:55:58 PM: Load paths:
12:55:58 PM:   /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-theme-primer-0.5.3/_sass
12:55:58 PM:   /tmp/jekyll-remote-theme-20191003-1412-1p2nodz/_sass on line 1
12:55:58 PM: Skipping functions preparation step: no functions directory set
12:55:58 PM: Caching artifacts
12:56:00 PM: Error running command: Build script returned non-zero exit code: 1
12:56:00 PM: Failing build: Failed to build site
12:56:00 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
12:56:00 PM: Finished processing build request in 31.448512657s
```

I don't have time to personally look at this further until the weekend, but you're free to keep trying at it until the Netlify deploy builds. :smile:

This is a great time to get CircleCI working (#50) so the build log can be live and it'll help debug issues like this. I'll also try to get that working over the weekend but would love if someone else could contribute the config file as well. :smile:

**Comment by crweiner** [comment]
I just added a deploy preview notification from Netlify when a build fails and I changed the build logs to be public, so hopefully that'll automatically help you out for this PR. :smile:

**Comment by dehrax** [comment]
Turns out that having a local dev environment makes things so much easier :smile:

**Pull request merged**
