### PR TITLE
Updated Meilisearch swag with accurate info

### PR DESCRIPTION
**Pull request by ferdi05**
As confirmed on [Meilisearch blog](https://blog.meilisearch.com/hacktoberfest-2022-mid-october-update/)

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hello @ferdi05! 👋 Thank you to everyone at Meilisearch for going above and beyond for Hacktoberfest 2022! Very happy to hear that you've been getting some great PRs, and I hope we have played our little part in getting you connected with new contributiors. ❤️

I personally love the uniqueness of your swag for this year and will take a look to see if I can personally help out with some meaningful PRs too. 😊

Happy Hacktoberfest, and thanks again for being an important part of Hacktoberfest 2022!

**Comment by ferdi05** [comment]
Thanks so much for the kind words Chandler!
Well, if you want to measure the impact you had on our company so far, I suggest you to read [this](https://blog.meilisearch.com/hacktoberfest-stories-from-contributor-to-manager/).
I must say I learned only a few days ago that it was how Bruno found Meilisearch... that's quite a success story and we definitely owe you one.
We'll find a way to send you some swag, whether you participate or not :)

**Comment by crweiner** [comment]
This absolutely made my day, @ferdi05! 💗 

awesome

That's **_exactly_** what I hoped this List would be; a great way to showcase companies going the extra mile for Hacktoberfest and to foster connections between contributors and those companies. I'm so, so happy that my project had such a positive impact at Meilisearch by sending Bruno your way!! 😄 That's so incredible and shows the power of open-source (and swag!! 😎).

I'll tweet about this and share your blog post, if you don't mind!

I'll also never turn down swag 😆 , feel free to reach out via [Twitter DM](https://twitter.com/c_dubbs) or email for my details, and I'll still look to see if I can make some meaningful contributions too!

**Comment by ferdi05** [comment]
Sure, feel free to share this!

Sending a Twitter DM your way :)

**Pull request merged**
