### PR TITLE
i have changed footer position to fixed

### PR DESCRIPTION
**Pull request by keval2232**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [ ] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [ ] I'm not adding a company from the blocklist
3. [ ] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by DaffyTheDuck** [comment]
Are you making the same PR from different account? or it's just coincidence

**Comment by keval2232** [comment]
No I have only one account

**Comment by DaffyTheDuck** [comment]
Oh! so your name and the person making this #346 is same?

**Comment by keval2232** [comment]
I don't know name of him but it can be same name of diffrent persons

**Comment by crweiner** [comment]
Hi @keval2232 :wave:

The footer position needs to remain ```static```, not ```fixed```. For small screens, like the 13' MacBook Pro, the footer will smash into the left side of the screen if set to ```fixed```. Take a look at the Netlify preview:

Screen Shot 2020-10-09 at 8 24 48 AM

This was fixed all the way back in PR #122.

So, I won't be able to pull this into the Swag List, but I hope you have a great Hacktoberfest. 👍

**Pull request closed without merging**
