### PR TITLE
Added JetBrains

### LINKED ISSUE #259: Add JetBrains to the 2020 Hacktoberfest Swag List
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://www.jetbrains.com/lp/hacktoberfest-2020/), [JetBrains](https://www.jetbrains.com/) is participating in Hacktoberfest 2020 by giving away their own swag.

Please add JetBrains to the 2020 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

### PR DESCRIPTION
**Pull request by DaffyTheDuck**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

Closes #259

### CODE REVIEW

**Comment by DaffyTheDuck** [comment]
feel free to suggest changes :smile: @crweiner

**Comment by crweiner** [comment]
I'll review the commit later tonight, but can you please work on the mdl issues flagged by Code Climate? Thank you! 👍

**Comment by DaffyTheDuck** [comment]
yes fixing those

**Comment by DaffyTheDuck** [comment]
Done @crweiner  :smile:

**Comment by crweiner** [comment]
Hi @DaffyTheDuck! Thank you so much for your contribution to the Hacktoberfest Swag List! I appreciate you working hard to make this project even more awesome! 💪 You rock!

you rock

**Comment by DaffyTheDuck** [comment]
Thanks :tada:

**Pull request merged**
