### PR TITLE
update: add resuminator, appflowy, codédex  and Razorpay to the list

### LINKED ISSUE #684: Add Resuminator to the Hacktoberfest Swag List
[Resuminator](https://www.resuminator.in/) is participating in inviting everyone to open new issues, start discussions and contribute to the project by submitting PRs against any `hacktoberfest` labelled issues. 

As per their [announcement](https://github.com/resuminator/resuminator/issues/149) any and all types of contributions are welcome. From fixing docs to developing features, you can find the issue level and the expected level of knowledge required for each level discussed in the announcement page. 

Designers also get an opportunity to contribute to designing the swag they plan to distribute to all the contributors. 

This issue is open for anyone who wants to contribute to this repo. 

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

### PR DESCRIPTION
**Pull request by vimode**
1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

closes #684 

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by vimode** [comment]
Updated to add AppFlowy

closes #686 

AppFlowy are not running any exclusive Hacktoberfest event nor giving any special hacktoberfest swag but they give a special t-shirt to contributors all year long.  

I remember from your Kong related discussion that you approve of promotions which coincide well with hacktoberfest, so I added to the list.

**Comment by vimode** [comment]
closes #684, closes #686, closes #687

**Comment by vimode** [comment]
Added Razorpay
closes #688

**Comment by crweiner** [comment]
Another great PR! Thank you for all your help this year, @vimode!

yes

**Pull request merged**
