### PR TITLE
Added Bagisto

### PR DESCRIPTION
**Pull request by devansh-webkul**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
I'm going to need a little bit more info, @devansh-webkul. The Swag List requires that we know the amount of PRs a person needs, if there's different PR requirements for each item of swag you have, signup form, ```Hacktoberfest``` labeled issues, etc. Plus, I need to verify that you are offering unique swag by including a blog post, tweet, or something documenting your swag for the year. 

Additionally, the [Contributing.md](https://hacktoberfestswaglist.com/contributing) file should be followed for adding someone new to the Swag List. Please make sure that you read the Contributing.md file and can provide as much info as possible. 👍  Thanks! 😄

**Comment by devansh-webkul** [comment]
Hi @crweiner 

These are the info, i am just confirming first from you then update this PR,

- On 4 successful PR merges, Bagisto will provide T-Shirt, stickers, notebook, pen and Bagisto elephant.

- Only those PRs are accepted which are marked  with 'Hactoberfest' label and we have added difficulty level to each issues. So user can track the issues.

- Although we have added 'hactoberfest' topic in our repo, but we will consider only PR which are labelled with 'Hactoberfest. Below is the link.

- Reference Link: https://github.com/bagisto/bagisto/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest

If these info is needed in this PR, then i will update this.

**Comment by devansh-webkul** [comment]
Tommorow morning i will update this PR, as i mentioned instructions above. I hope these are the info you needed.

Anymore info needed then let me know.

**Comment by devansh-webkul** [comment]
Okay, I have updated the PR, for proof I am updating the `Contributing.md` file of Bagisto.

**Comment by devansh-webkul** [comment]
Hi @crweiner,

For proof I just added the rules in the front page `ReadMe.md` file, below is the link,
https://github.com/bagisto/bagisto/blob/master/README.md

If you still need blogs and tweets then I need to contact my team first.

Let me know, if you need anything else.

**Comment by crweiner** [comment]
That's **perfect** @devansh-webkul, thank you so much! If you add Bagisto to the _Least Involvement to Most Involvement_ section of the Swag List, I can then get this merged and live! Thanks so much!! 👍

**Comment by devansh-webkul** [comment]
@crweiner,

I have added in the mentioned topic.

**Comment by crweiner** [comment]
Beautiful job there, @devansh-webkul! Thank you so much for working with me to get Bigisto on the 2021 Hacktoberfest Swag List! I hope we can send some great PRs your way!! Thank you for celebrating Hacktoberfest and going the extra mile by offering your own swag! 🎉 🎉 

you are a star

**Pull request merged**
