### PR TITLE
Add Gita To The Hacktoberfest Swag List

### PR DESCRIPTION
**Pull request by Rahul-Kumar-prog**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by Rahul-Kumar-prog** [comment]
Hey @crweiner please review my PR and if its need to have any changes then let me know. and if not then please accept this PR.

**Comment by Rahul-Kumar-prog** [comment]
#630

**Comment by Rahul-Kumar-prog** [comment]
#630

**Comment by Rahul-Kumar-prog** [comment]
#630

**Comment by crweiner** [comment]
Hello @Rahul-Kumar-prog! 👋 Thank you for your PR to add Gita to the Hacktoberfest Swag List! I appreciate your contribution and hope to send some meaningful PRs their way! 🎉 

Have a great Hacktoberfest! 🎃 

dancing pumpkin

**Pull request merged**
