### PR TITLE
Add Novu to swag list

### LINKED ISSUE #578: Add Novu to the 2022 Hacktoberfest Swag List!
A good first issue for people celebrating Hacktoberfest!

Per [here](https://github.com/novuhq/novu#readme), Novu is participating in Hacktoberfest 2022 by giving away their own swag. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

### PR DESCRIPTION
**Pull request by adetoye-dev**
Closes #578 

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [ x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [ x] I'm not adding a company from the blocklist
3. [x ] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by letsintegreat** [comment]
I don't believe that's the correct way to add links in markdown. The stuff that goes inside square brackets is a title, not the link itself.

**Comment by adetoye-dev** [comment]
> I don't believe that's the correct way to add links in markdown. The stuff that goes inside square brackets is a title, not the link itself.

Alright, thanks.

I'll fix that 👍

**Comment by Rutam21** [comment]
Also, where did you find the swag details ? I don't think they have mentioned it yet. I just asked for the details on their Discord and was waiting for a response to raise the PR. Kindly check if someone has commented on the issue to work first. Thanks.

**Comment by crweiner** [comment]
Seems like we do need a little bit more info. Do they have a tweet/blog post about what they're doing for Hacktoberfest beyond that Readme header?

**Comment by adetoye-dev** [comment]
> Seems like we do need a little bit more info. Do they have a tweet/blog post about what they're doing for Hacktoberfest beyond that Readme header?

That was all the details I could find, I'll update the doc if I do get extra information.

No, they don't. Just the details on their readme header

**Comment by crweiner** [comment]
I'd like to hold off a little bit then until we can gather some more information. This project sends lots of people to the organizations on the Swag List each year, and I need to make sure that the companies on this list follow Hacktoberfest's rules. 

I'll leave this PR open for now, and please see what other info you can gather from them to verify swag, requirements, etc. 👍

**Comment by adetoye-dev** [comment]
> I'd like to hold off a little bit then until we can gather some more information. This project sends lots of people to the organizations on the Swag List each year, and I need to make sure that the companies on this list follow Hacktoberfest's rules.
> 
> I'll leave this PR open for now, and please see what other info you can gather from them to verify swag, requirements, etc. 👍

Alright 👍

**Comment by crweiner** [comment]
Hello again @adetoye-dev! 👋 I greatly appreciate your PR to add Novu to the Swag List! I received several PRs to add them and the one in #585 had a little more detail and confirmation from one of their DevRel employees. I'll close this PR, but I don't want this to discourage you from submitting further meaningful PRs to my repo or Hacktoberfest-participating ones in general.

I highly encourage you to read all of the [Participation Rules](https://hacktoberfest.com/participation/) and make sure that the PRs you submit for Hacktoberfest are ones like you did here, where there is a meaningful contribution you are providing. Avoid repos where you are just getting a +1 to your PR count. ➕ 

Thank you again, and have a great Hacktoberfest! 🎃

**Comment by adetoye-dev** [comment]
Thanks 😇

**Pull request closed without merging**
