### PR TITLE
Added Scroll button 

### PR DESCRIPTION
**Pull request by codewithdev**
Added Scroll Button #193

### CODE REVIEW

**Comment by crweiner** [comment]
Take a look at the Netlify build and let me know if you think it's working as you intended.

**Comment by lex111** [comment]
Isn't it easier and better to just inject production-ready JS lib like [this one](https://github.com/vfeskov/vanilla-back-to-top)?

**Comment by crweiner** [comment]
@lex111 that would be much better for sure!

**Comment by crweiner** [comment]
Closing this PR as it seems to be stale. If someone wishes to add [Vanilla Back To Top](https://github.com/vfeskov/vanilla-back-to-top), I'd be all for it (or I can do it myself too :smile:).

**Comment by adriaanvermeire** [comment]
@crweiner can I add a Vanilla Back To Top button or has it already been done?

**Comment by crweiner** [comment]
> @crweiner can I add a Vanilla Back To Top button or has it already been done?

I'd love it if you would like to @adriaanvermeire! :smiley_cat:

**Pull request closed without merging**
