### PR TITLE
Add Supabase to the list

### PR DESCRIPTION
**Pull request by moingshaikh**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hey @moingshaikh! Thank you for your contribution to the Hacktoberfest Swag List! 👍 

I'm not sure if MojoAuth's offering counts as swag, so I'm not sure if they're a good fit for this List. Also, can you please Supabase to the _Least Involvement to Most Involvement_ section and remove the extra parenthesis around your text?

Be sure to follow the [Contributing guidelines](https://hacktoberfestswaglist.com/contributing) as that has all the info you'll need. 😄 

Thank you! Looking forward to having these fixed soon so we can get them merged!

**Comment by moingshaikh** [comment]
> Hey @moingshaikh! Thank you for your contribution to the Hacktoberfest Swag List! 👍
> 
> I'm not sure if MojoAuth's offering counts as swag, so I'm not sure if they're a good fit for this List. Also, can you please Supabase to the _Least Involvement to Most Involvement_ section and remove the extra parenthesis around your text?
> 
> Be sure to follow the [Contributing guidelines](https://hacktoberfestswaglist.com/contributing) as that has all the info you'll need. 😄
> 
> Thank you! Looking forward to having these fixed soon so we can get them merged!

Hi @crweiner, 

Sure. Let me update this accordingly. Thank you for your quick review and feedback.

**Review by moingshaikh — COMMENTED** [review]
Update PR #414

I have updated my code with format correction and list updation.

**Review by moingshaikh — COMMENTED** [review]
Style error in #414 fixed.

**Comment by crweiner** [comment]
Thank you so much @moingshaikh for taking the time to add Supabase to the Hacktoberfest Swag List! 🎉 🎉 🎉 I appreciate your contribution and hope you have a wonderful Hacktoberfest 2021!

thank you

**Comment by moingshaikh** [comment]
> Thank you so much @moingshaikh for taking the time to add Supabase to the Hacktoberfest Swag List! 🎉 🎉 🎉 I appreciate your contribution and hope you have a wonderful Hacktoberfest 2021!
> 
> thank you

You are welcome, @crweiner. More than happy to contribute to your awesome project.

If there is anything else I can contribute to, please feel free to let me know.

Have a great month ahead!

**Comment by crweiner** [comment]
@moingshaikh  You can always take a look at the [open issues](https://github.com/crweiner/hacktoberfest-swag-list/issues) to add other companies to the Swag List, and spread the word about this repo to other nerdy people interested in Hacktoberfest! 😄

**Comment by moingshaikh** [comment]
> @moingshaikh You can always take a look at the [open issues](https://github.com/crweiner/hacktoberfest-swag-list/issues) to add other companies to the Swag List, and spread the word about this repo to other nerdy people interested in Hacktoberfest! 😄

Will surely do :)

**Pull request merged**
