### PR TITLE
Added Devtron to the list

### PR DESCRIPTION
**Pull request by itsBaivab**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by vimode** [comment]
Devtron has provided more details about their participation in Hacktoberfest 2023. 

Can you please update all the information based on their [blog post](https://devtron.ai/blog/dive-into-open-source-joy-with-devtron-in-hacktoberfest-2023/)? 

Thank you.

**Comment by crweiner** [comment]
>Devtron has provided more details about their participation in Hacktoberfest 2023.

> Can you please update all the information based on their [blog post](https://devtron.ai/blog/dive-into-open-source-joy-with-devtron-in-hacktoberfest-2023/)?

Thank you so much, @vimode! 

Please be sure to fix the CodeClimate issues as well, @itsBaivab. 👍

**Comment by itsBaivab** [comment]
Updated Devtron with the new info and fixed the codeclimate issues

**Comment by crweiner** [comment]
Hi @itsBaivab and @SparklinStar! Thank you for working together to add Devtron to the Hacktoberfest Swag List!

I noticed that they added a signup form, so I modified your PR to add that here: 259692a47258cfed1f51457c29fb1758941508a5

Thank you to @vimode pointing me in that direction, now that the Devtron team updated their blog post with more info.

Let's get them on the list now! ✅ 

thank you

**Pull request merged**
