### PR TITLE
ArchivesSpace, Tripal, Aqua Security added

### PR DESCRIPTION
**Pull request by souravroy-test**
Added to the List
1.ArchivesSpace
2.Sensenet 
3.Tripal

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x]  I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by souravroy-test** [comment]
@crweiner can you check this out?

**Comment by crweiner** [comment]
Hey there @souravroy-test! I have had limited time today to review PRs and will do the bulk of them later. I see that Code Climate has flagged some errors that you'll need to fix, please.

Also, there will probably be additional merge conflicts that appear, so be ready to tackle those. 👍

**Comment by souravroy-test** [comment]
Actually, I could not figure out the conflict . That's why I mentioned you!

**Comment by crweiner** [comment]
Wow @souravroy-test! Thank you so much for adding 3 new companies to the 2020 Hacktoberfest Swag List! 🎉 That's an incredible contribution. ❤️ 

Have a marvelous Hacktoberfest!

you are awesome

**Comment by souravroy-test** [comment]
thanks!

**Pull request merged**
