### PR TITLE
Added Novu to the Hacktoberfest 2022 Swag List!

### PR DESCRIPTION
**Pull request by Rutam21**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Also, all the swag and event details are officially confirmed with the Novu team. This should fix https://github.com/crweiner/hacktoberfest-swag-list/issues/578

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
I recently posted in [this PR](https://github.com/crweiner/hacktoberfest-swag-list/pull/579#issuecomment-1264656652) that I'd like to hold off on adding Novu to the Swag List right now, pending some additional information regarding their Hacktoberfest participation. 👍

**Comment by Rutam21** [comment]
@crweiner I have seen that. But they have already posted their swag on Twitter and I have officially talked with them on Discord and confirmed their participation. You can find the tweet [here](https://twitter.com/novuhq/status/1576536573436637186).

**Comment by iampearceman** [comment]
Hey @crweiner, as Novu's spokesman, I can assure you that everything is correct, and we are participating fully.

**Comment by crweiner** [comment]
Hello again @Rutam21! 👋 And thank you very much for stopping by to take a look at this PR to confirm everything, @iampearceman! 😄 I love adding new organizations to the Hacktoberfest Swag List each year and I hope to send some meaningful PRs to Novu because of this List!

you rock

Thanks again all, and have a happy Hacktoberfest! 🎉

**Pull request merged**
