### PR TITLE
Added Kong to the list for Hacktoberfest 2019

### PR DESCRIPTION
**Pull request by thenewmona**
Added Kong to this for a contributor T-shirt

### CODE REVIEW

**Comment by crweiner** [comment]
Hay there @thenewmona! Thanks for your contribution! I'm awaiting an official blog post by Kong in Issue #52 before merging them here as I want to see if they are offering unique swag for Hacktoberest or if it's their "normal" swag that they offer year-round. If you see something, let me know! Thanks!

**Comment by crweiner** [comment]
Hi again @thenewmona and @Ramona-Saintandre, do you have some time to clear the CodeClimate markdownlint issues? I'd love to get Kong on the list. Thanks!

**Comment by moingshaikh** [comment]
> Hi again @thenewmona and @Ramona-Saintandre, do you have some time to clear the CodeClimate markdownlint issues? I'd love to get Kong on the list. Thanks!

Hi @crweiner, 

Regarding fixing typos and formatting issues on open PR, I would like to know if only the contributor that opened that particular PR can fix them or anyone can fix them?

Since I have already made my contribution, I wanted to give others opportunity to contribute as easily much as possible, and hence I wanted to see if I can fix CodeClimate issues on any open PRs so their PRs can get merged asap.

**Comment by crweiner** [comment]
Hi @moingshaikh, it appears like this PR is going stale so you're welcome to help out.

It is likely easier for you to do your own PR from the up-to-date swag list than fix this particular one, but that's up to you. :smile:

**Comment by moingshaikh** [comment]
> Hi @moingshaikh, it appears like this PR is going stale so you're welcome to help out.
> 
> It is likely easier for you to do your own PR from the up-to-date swag list than fix this particular one, but that's up to you. 😄

Thanks for the response, @crweiner I also think doing PR from latest swag list will be easier. I am going to work on this very soon; also, I will see if there are any other PRs from other contributors needing any formating/grammatical fixes.

**Comment by crweiner** [comment]
Stale and closed

**Pull request closed without merging**
