### PR TITLE
Added Valor Software

### PR DESCRIPTION
**Pull request by WilChrist**

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @WilChrist!

Please make sure to break up the different "levels" fo swag that Valor Software is offering in the "Least Involvement to Most Involvement" section of the swag list and be sure to follow our [Contributing guidelines here](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md).

Also, please resolve the merge conflicts so I can get Valor added to the list as soon as you complete these changes. Thank you!

**Comment by WilChrist** [comment]
@crweiner i think everything is ok now, right ?

**Comment by crweiner** [comment]
I reached into your project to fix the merge conflicts, so we are good to go now! Thank you for your hard work!! Be proud of your contribution and have a wonderful Hacktoberfest! :+1: :smile: :fireworks: 

thumbs up

**Comment by WilChrist** [comment]
Thanks. @crweiner Do you not what "maturing (and the count down associated)" means in ours hacktoberfest profile?

**Comment by crweiner** [comment]
Where are you seeing that? Is it at [here](https://hacktoberfest.digitalocean.com/profile)? I'm not sure what you mean or where you're seeing that.

**Comment by rafaeelaudibert** [comment]
> Thanks. @crweiner Do you not what "maturing (and the count down associated)" means in ours hacktoberfest profile?

This year, repo maintainers have 7 days to let Digital Ocean know if the PR you created is to be or not to be counted against your quota of 4 PR's for the Hacktoberfest. After this 7 days window is gone, the PR's will then count.

**Comment by crweiner** [comment]
Ahhh, good to know @rafaeelaudibert. Thanks for clarifying! Got to get my `invalid` labels slapped on ASAP then. :+1:

**Pull request merged**
