### PR TITLE
Correct requirements and swag for source{d}

### PR DESCRIPTION
**Pull request by MaskyS**
>We’re thrilled to be participating in this year’s Hacktoberfest. Any contributor who gets three pull requests submitted and merged in any source{d} repo between October 1 and October 31 will receive a limited edition T-shirt as well as one sticker for those who get at least one pull requests merged.

https://medium.com/sourcedtech/celebrating-open-source-with-hacktoberfest-2018-7283cfc6666b

### CODE REVIEW

**Comment by crweiner** [comment]
Thank you so much @MaskyS!! :+1:  I couldn't find the specifics anywhere, and it turns out it was right under my nose. 

I'd love to get this merged, so could you please double check your Markdown list formatting, please? You need to have a little ```-``` symbol and a space to the left of the Sticker and T-shirt sub-points in order to get the bullet points to appear. It should look like this in your code:

```
- Example 1
- Example 2
   - Example 2.1
   - Example 2.2
- Example 3
```
That generates a list that looks like this when rendered on GitHub:
- Example 1
- Example 2
   - Example 2.1
   - Example 2.2
- Example 3

If making these changes directly on GitHub.com, be sure to use the "Preview" tab near the top of the editor so you can double check that it looks perfect.

Also, be sure to add your name to the CONTRIBUTING.md file so you can get some extra credit! :smile: 

Thanks again and give me the heads up when you've made the adjustments. You rock! :1st_place_medal:

**Comment by MaskyS** [comment]
All done :)

**Comment by crweiner** [comment]
Thanks for making that change! Would you like to add yourself to the bottom of `CONTRIBUTING.md`?

**Comment by crweiner** [comment]
You rock @MaskyS! Thanks again for your contribution! :+1: :boom:

**Pull request merged**
