### PR TITLE
Add Pusher to the Swag List

### PR DESCRIPTION
**Pull request by moingshaikh**
Added Pusher to the list.

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Review by moingshaikh — COMMENTED** [review]
Training space removed.

**Comment by crweiner** [comment]
Hello @moingshaikh! 👋 Thank you for adding Pusher to the Hacktoberfest Swag List! 🎉 

awesome

I hope we can send lots of meaningful contributions their way! Thank you for helping to connect contributors to find Pusher!

**Comment by moingshaikh** [comment]
> Hello @moingshaikh! 👋 Thank you for adding Pusher to the Hacktoberfest Swag List! 🎉
> 
> awesome [ awesome ](https://camo.githubusercontent.com/ee5650de680950814c7a20f5642f11a0d66dae4b5769572e8ef451f6f24ee96a/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3256703055784e6341385445512f67697068792e676966) [ ](https://camo.githubusercontent.com/ee5650de680950814c7a20f5642f11a0d66dae4b5769572e8ef451f6f24ee96a/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3256703055784e6341385445512f67697068792e676966)
> 
> I hope we can send lots of meaningful contributions their way! Thank you for helping to connect contributors to find Pusher!

Awesome!! Thanks a lot for merging.

I look forward to contributing more. And this is my second year with your awesome repo contributing to Hacktoberfest :)

Have a great Hacktoberfest ahead!

**Comment by britneycodes** [comment]
Thanks for adding us to the list! @moingshaikh and @crweiner 🎃

**Pull request merged**
