### PR TITLE
favicon icon

### PR DESCRIPTION
**Pull request by vishveshjain**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hello @vishveshjain! 👋 Thank you for your PR (which I think is your first one?)!

I'd encourage you to review Issue #547 to make sure that you follow everything that is needed to properly add a Hacktoberfest-focused favicon.

**Review by crweiner — CHANGES_REQUESTED** [review]
This icon seems to have nothing to do with Hacktoberfest. Please read through the proper Issue and my comment on the PR.

**Comment by Asmit2952** [comment]
I can jump on this

**Comment by crweiner** [comment]
> I can jump on this

New PRs are always accepted, @Asmit2952! Especially at the start of Hacktobefest, getting the site setup ASAP is very important.

**Comment by Asmit2952** [comment]
Hey @crweiner you can now close this PR!

**Comment by crweiner** [comment]
The favicon has now been added in PR #576, thank you!

**Pull request closed without merging**
