### PR TITLE
Added Accord Project

### PR DESCRIPTION
**Pull request by JordanJay02**
Added AccordProject to the list, and myself to the list of contributors

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @JordanJay02!!! Thank you so much for contributing to the Hacktoberfest Swag List! I must say that I'm very proud to be the recipient of your first pull request here on GitHub! Be sure to signup for the official Hacktoberfest event and come back after 10/1 to make even more contributions and earn your sweet official swag.

There's a few things that I'd love for you to tweak before we can get your contribution merged onto the official list. I'll make some recommendations here in a bit (don't have time at this exact moment) and when you have the chance to make those changes then we'll get your PR merged. :smile: So be on the lookout for that soon!

Thanks so much again! You rock!!
You rock

**Comment by crweiner** [comment]
Are you still working on this @JordanJay02? Just wanted to ping you in case you'd rather have someone else take a stab at it.

**Comment by JordanJay02** [comment]
> Are you still working on this @JordanJay02? Just wanted to ping you in case you'd rather have someone else take a stab at it.

Yep, I will make the changes at some point this week, I'm fairly busy at the moment though due to college.

**Comment by crweiner** [comment]
> > Are you still working on this @JordanJay02? Just wanted to ping you in case you'd rather have someone else take a stab at it.
> 
> Yep, I will make the changes at some point this week, I'm fairly busy at the moment though due to college.

Hi Jordan! I appreciate you getting back to me. If you're too busy at the moment, then I'll open this up to someone else to also help out. I'd like to get them on the list sooner rather than later. Unfortunately, your PR was before Hacktoberfest started anyway, so if you were looking for this contribution to count towards your official swag for the holiday; you were a a tad bit early. :disappointed:

**Comment by crweiner** [comment]
Accord now added in #111

**Pull request closed without merging**
