### PR TITLE
Added CircleCI to the 2020 Hacktoberfest Swag List

### LINKED ISSUE #257: Add CircleCI to the 2020 Hacktoberfest Swag List
A good first issue for people celebrating Hacktoberfest! If you want for this to count towards Hacktoberfest, please submit your PR on October 1st!

Per [here](https://hacktoberfest.circleci.com/), [CircleCI](https://circleci.com/) is participating in Hacktoberfest 2020 (which they dub Orbtoberfest) by giving away their own swag.

Please add CircleCI to the 2020 list following the formatting in the [CONTRIBUTING.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file.

You will need to locate the type of swag being offered and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here](https://hacktoberfest.digitalocean.com/).

### PR DESCRIPTION
**Pull request by Ankur-Khandelwal**
Resolves #257

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @Ankur-Khandelwal! Thank you for contributing to the Hacktoberfest Swag List!

Can you please double check and make sure that your PR follows the [Contributing](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) guidelines and has every feature it needs? The other items on the List are great jumping off points. Also, please tackle the issues flagged by Code Climate.

Thank you! 😄

**Comment by Ankur-Khandelwal** [comment]
Hi @crweiner ! I went through the Contibuting Guidelines again and based on that, I have added some commits. And I have fixed the issues flagged by Code Climate as well. 

Please go through them and let me know of further improvements.

Happy to be a part of Hacktoberfest 2020 :)

**Comment by crweiner** [comment]
Hey @Ankur-Khandelwal! Thank you for your hard work adding CircleCI to the Hacktoberfest Swag List! 👍 

I had multiple PRs to add CircleCI, so I can't merge them all. I appreciate your time and effort working on this PR, but sadly I'll have to close it. Don't worry, this will still count towards Hacktoberfest because you did submit a real PR that followed the [Hacktoberfest standards](https://hacktoberfest.digitalocean.com/details#quality) 😄 

Thank you again, I hope you understand, and have a great Hacktoberfest!

**Comment by Ankur-Khandelwal** [comment]
Thank You @crweiner . 

Actually it was written in FAQs section of Hacktoberfest Website that, "_As long as they’ve been opened and marked as ready-for-review between the beginning of October 1 and the very end of October 31, they count_" So wanted to confirm once again that even after closing the PR, it will be counted.

Anyways, I am enjoying participating in Hacktoberfest 😇.

**Pull request closed without merging**
