### PR TITLE
Added Vonage/Nexmo

### PR DESCRIPTION
**Pull request by khushijindal**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Review by avats-dev — APPROVED** [review]
Looks good to me @khushijindal :tada: based on netlify deploy.

**Comment by ruskibenya** [comment]
Yay! @khushijindal, thank you from your friends at Vonage!

**Comment by ruskibenya** [comment]
@khushijindal gave ya some twitter love 💕 

https://twitter.com/VonageDev/status/1311446934633304066?s=20

**Comment by crweiner** [comment]
Hey there @khushijindal! Thank you so much for your contribution to the Hacktoberfest Swag List! I appreciate you taking the time to add Vonage/Nexmo to the list! 👍 😄 
@avats-dev, thank you too for the extra pair of eyes looking things over. I can use all the help I can get during Hacktoberfest 😅 
And @ruskibenya, *WOW*! Thank you so much! You just made my night! That's so freaking awesome that you would shout out my little project here and thank you for recognizing the work of others. 😄  I hope that the Swag List can drive some great meaningful contributions to your repos an I'm honored to play my part during Hacktoberfest. 🎃 🎉 

Let's get this baby merged!
Now we're rocking

**Comment by khushijindal** [comment]
Thank you @crweiner for the amazing opportunity. ⭐🎉
@ruskibenya Thank you so much for the shout-out for my first PR itself. I am so so happy with this start to my journey. ❤️✨
Thanks @avats-dev for reviewing the PR. 🙂

**Pull request merged**
