### PR TITLE
Indeed, Mattermost, Uno, Specflow Added 

### PR DESCRIPTION
**Pull request by souravroy-test**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Sweet! Thanks for all of your contributions and PRs @souravroy-test! I'll take a deeper look at this PR later on tonight but first glance looks great. 👍 Would you be able to tackle the Code Climate flags please?

**Comment by souravroy-test** [comment]
Thanks. If, it's not complex then I can.Learning how to contribute!

**Comment by crweiner** [comment]
> Thanks. If, it's not complex then I can.Learning how to contribute!

You're doing a great job! 😄 I appreciate you adding genuine value to this project by finding and listing companies celebrating Hacktoberfest this year. 💜 

To give you a little bit of background, this project uses a language called [Markdown](https://en.wikipedia.org/wiki/Markdown) as the raw "code" that gets turned into the website [Hacktoberfestswaglist.com](https://hacktoberfestswaglist.com), which uses HTML. In order for Markdown to get converted into HTML, we need to use a program called a [static site generator](https://www.netlify.com/blog/2020/04/14/what-is-a-static-site-generator-and-3-ways-to-find-the-best-one/); the one that this particular project uses is [Jekyll](https://jekyllrb.com/).

In order to make sure that the Markdown -> HTML conversion goes smoothly, you have to follow some rules. If your Markdown is messed up, then the site won't be converted properly into HTML.

That's where Code Climate comes into the picture. Code Climate is running a little program called [markdownlint](https://github.com/DavidAnson/markdownlint) (mdl) which checks the Markdown file to make sure that it follows all the right rules. So, when Code Climate gives you a flag, it is because it has found something that needs to be fixed in the Markdown so that it can follow the rules.

Most of yours are just related to some spacing errors. This can happen using an editor like Atom, which doesn't play all that nicely with mdl. For example, Code Climate has flagged this:

Screen Shot 2020-10-02 at 11 33 33 PM

That shows that [Line number 133 of your contribution](https://github.com/crweiner/hacktoberfest-swag-list/pull/311/files#diff-04c6e90faac2675aa89e2176d2eec7d8R133) has a space after the period. That's all! 😄 Just clearing that space after the period at the end of the sentence fixes that. 👍 

Does that make some more sense?

**Comment by souravroy-test** [comment]
Yes, now it makes sense. 
Thanks, that means a lot! I read somewhere contributing to open-source you can learn a lot. just following that process!

**Comment by crweiner** [comment]
Hey @souravroy-test! 👋 Sorry this took a while to get back to you! A *HUGE* thank you for adding so many companies to the Swag List!! 👍 🎉 😄 

You rock! Have a marvelous Hacktoberfest!

thank you

**Pull request merged**
