### PR TITLE
Added LeapFrog's Frogtoberfest to the list according to issue #806

### PR DESCRIPTION
**Pull request by SanchitMahajan236**
I have added the LeapFrog organization's Frogtoberfest to the list according to issue #806 and have followed the format given in contributing.md

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by vimode** [comment]
FYI, as mentioned in #806 the sign up(form) link is still not made accessible.

**Comment by SanchitMahajan236** [comment]
I tried it and the form is restricted but ig they only allow registrations before the start of the event and moreover I search the site so that I can contact someone to get a clarity but couldn't find anything.

**Comment by SanchitMahajan236** [comment]
I think I will contribute to another issue

**Comment by SanchitMahajan236** [comment]
@vimode I talked to the team of Frogtoberfest about the issue regarding the registration form and they told me that the registrations have been closed for this year. So, you can tell me what should we do about this PR then.

**Comment by vimode** [comment]
Great job  getting us this update @SanchitMahajan236
If people can't register anymore, then no point adding it to the list. 

I think its better not to add it to the list. But we will wait for @crweiner to make that call. 
Don't worry he take the necessary actions on this PR and the corresponding issue.

**Comment by SanchitMahajan236** [comment]
Sure, I will be waiting for @crweiner reply.

**Comment by crweiner** [comment]
Howdy @SanchitMahajan236 and @vimode!

> I talked to the team of Frogtoberfest about the issue regarding the registration form and they told me that the registrations have been closed for this year. 

Ahh, that's too bad. We do have some organizations on the Swag List that have limited swag to provide, or short windows to contribute, and that's totally fine! But if no one can participate any further, then I'll have to think a bit about whether or not to add them. I don't want to point contributors to a project if the project isn't looking for more help.

Let me think about this for a bit. In the meantime, can you please add that they are not currently accepting new participants to the leaderboard?

**Comment by SanchitMahajan236** [comment]
> Howdy @SanchitMahajan236 and @vimode!
> 
> > I talked to the team of Frogtoberfest about the issue regarding the registration form and they told me that the registrations have been closed for this year.
> 
> Ahh, that's too bad. We do have some organizations on the Swag List that have limited swag to provide, or short windows to contribute, and that's totally fine! But if no one can participate any further, then I'll have to think a bit about whether or not to add them. I don't want to point contributors to a project if the project isn't looking for more help.
> 
> Let me think about this for a bit. In the meantime, can you please add that they are not currently accepting new participants to the leaderboard?

I have added that they are not accepting new participants as you asked @crweiner.
Can you please confirm what to do with this PR as soon as possible ? 
As I want to generate a PR for another issue but cannot as I committed the changes on main branch in my forked repo, so I face  an issue.

**Pull request closed without merging**
