### PR TITLE
Add CodeSee to the Swag List

### PR DESCRIPTION
**Pull request by tacoelho**
Add OSS Port / CodeSee to the 2021 Hacktoberfest Swag List! #445 

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [ x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [ x] I'm not adding a company from the blocklist
3. [ x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Review by jleven — CHANGES_REQUESTED** [review]
Thanks so much for adding oss-port to this!

Just one detail: the requirement isn't PRs on the oss-port project. It's to contribute PRs to *any project listed on oss-port.com*!  Would you mind making that quick correction?

**Comment by tacoelho** [comment]
Changes made @jleven @ramonh

**Comment by crweiner** [comment]
WOW! This is some great teamwork! Thank you @tacoelho for the PR, and @jleven and @ramonh for your assistance getting CodeSee on the Hacktoberfest Swag List! 🎉 🎉 🎉  You all rock, and thank you for going out of your way for some great DevRel, gentlemen! 👍 😄 

Happy to get CodeSee on the Swag List and I hope we can send some great PRs your way and for everyone else on OSS Port! 🎆 Happy Hacktoberfest! 🎃 

teamwork

**Comment by ramonh** [comment]
Woopwoop! Looking forward to this collab so much, thank you so much @crweiner !! 💜

**Pull request merged**
