### PR TITLE
Add refine to the company swag list

### LINKED ISSUE #616: Add Refine to the Hacktoberfest Swag List
A good first issue for people celebrating Hacktoberfest!

Per [here](https://refine.dev/blog/hacktoberfest-refine/), Refine is joining in on the Hacktoberfest fun for the first time by giving away their own swag for meaningful contributions. 😄

Please add them to the 2022 list following the formatting in the [CONTRIBUTING.md file.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md)

You will need to locate the type of swag being offered, their requirements, and a link to their signup form (or some info on how they are tracking contributors).

Be sure to register for Hacktoberest first by [clicking here.](https://hacktoberfest.com/)

### PR DESCRIPTION
**Pull request by XoMute**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [X] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [X] I'm not adding a company from the blocklist
3. [X] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

Closes #616

### CODE REVIEW

**Comment by XoMute** [comment]
Closes #616

**Comment by XoMute** [comment]
@crweiner It seems like `CodeSee Map` job had some issues while executing. Could you please restart it to see if it was fixed?

**Comment by crweiner** [comment]
> @crweiner It seems like Github doesn't see new changes to my fork. Could that be because of closing and re-opening the PR? Would it be ok if I create a new one?

Yes, absolutely @XoMute! Feel free to do whatever you need (rebase, delete and re-fork, new PR, etc). 👍

**Comment by XoMute** [comment]
@crweiner Here's [the new PR](https://github.com/crweiner/hacktoberfest-swag-list/pull/643), everything seems ok now. Can you close this PR when needed? And sorry for the trouble, this process could've been much easier 😅

**Comment by crweiner** [comment]
No worries, all good! I'll close this PR and add your new one to my to-do list. 📜

**Pull request closed without merging**
