### PR TITLE
fixed Devfolio Notes

### LINKED ISSUE #293: Devfolio doesn't ships outside India!
It is clearly mentioned in the notes on the Devfolio page [here](https://devfolio.co/blog/devfolio-hacktoberfest-2020) that they won't be able to ship outside India, this needs to be added to notes. 

Capture

### PR DESCRIPTION
**Pull request by parshnt**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

This fixes #293

### CODE REVIEW

**Comment by parshnt** [comment]
@crweiner please have a look.

**Comment by crweiner** [comment]
Hi @parshnt! That's a really great catch, thank you so much! ❤️ Can you please also make the correction to Devfolio's entry in the "Least Involvement to Most Involvement" section? That way we can make sure that it's totally corrected. 

Let me know when you're ready for me to take a look! 👀

**Comment by crweiner** [comment]
@parshnt I just saw from your same note, the top 50 contributors will also get a t-shirt. Would you be able to update Devfolio 's entries on the list to reflect that as well?

**Comment by parshnt** [comment]
Hi @crweiner,

I made the changes, let me know if anything else needs to be added :)

**Comment by crweiner** [comment]
Thank you so much for fixing those issues, @parshnt! I appreciate you taking the time to help out this little project and I hope you have a great Hacktoberfest! 👍 😄 

thank you

**Pull request merged**
