### PR TITLE
Add Twilio to swag list.

### PR DESCRIPTION
**Pull request by code-monk08**
Happy Hacktoberfest!

### CODE REVIEW

**Comment by crweiner** [comment]
Hay there @code-monk08! I'm very excited to see Twilio participate again this year for Hacktoberfest!! Thanks for taking the time to add them to the list here!

If I'm reading their blog post correctly, its one merged PR for the sticker pack, and 2 merged PRs for the socks, correct? If so, can you please split up the swag into two areas under the **Least Involvement to Most Involvement** section following the [Contributing guidelines](https://hacktoberfestswaglist.com/contributing)? Could you also move the signup form link from **Requirements** to **How to sign up**?

Thanks again! :+1: Looking forward to those changes so we can get this merged and live!

**Comment by code-monk08** [comment]
> If I'm reading their blog post correctly, its one merged PR for the sticker pack, and 2 merged PRs for the socks, correct?

well, I see the same but for two PRs they will send a pair of socks along with a sticker pack, I guess. what do you think?

@crweiner

**Comment by crweiner** [comment]
Thanks again @code-monk08 for making those changes! I've fixed the merge conflicts and tweaked some formatting so now we can push this live! 

This list is made better by people like you, so thank you so much and enjoy Hacktoberfest 2019!!

you're awesome

**Comment by code-monk08** [comment]
Thanks for putting this list down in first place :1st_place_medal: :)
@crweiner

**Pull request merged**
