### PR TITLE
Added Taipy to the Hacktoberfest Swag List

### PR DESCRIPTION
**Pull request by ansarisadaffatima**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Closes: #838 

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by ansarisadaffatima** [comment]
Hi @vimode 

Kindly please review the PR. Please let me know incase of any issue.

Thanks,
Sadaf

**Comment by vimode** [comment]
Hey @ansarisadaffatima 

Please only add Taipy without changing the formatting of the other items. 

Your PR  has formatted a lot of things in other items which changes the way the list is rendered.  Every PR generates a preview build for you to check. 
If you check the [preview build](https://deploy-preview-839--hacktoberfest-swag-list.netlify.app/list) of this PR you will notice it has disturbed  formatting of many items which makes some of the particulars of the list items not render with proper indentation. 
Compare the preview build with the [live version](https://hacktoberfestswaglist.com/list/) and you will see the difference. 

Now you might not have done this intentionally and your code editor's autoformatter might have formatted it, so can you disable the auto autoformat option and just add Taipy? 

Thank you.

**Comment by ansarisadaffatima** [comment]
> Hey @ansarisadaffatima
> 
> Please only add Taipy without changing the formatting of the other items.
> 
> Your PR has formatted a lot of things in other items which changes the way the list is rendered. Every PR generates a preview build for you to check. If you check the [preview build](https://deploy-preview-839--hacktoberfest-swag-list.netlify.app/list) of this PR you will notice it has disturbed formatting of many items which makes some of the particulars of the list items not render with proper indentation. Compare the preview build with the [live version](https://hacktoberfestswaglist.com/list/) and you will see the difference.
> 
> Now you might not have done this intentionally and your code editor's autoformatter might have formatted it, so can you disable the auto autoformat option and just add Taipy?
> 
> Thank you.

HI @vimode 

Your suggestion helps me. Due to some extension its formatted all code. Have disabled and tried. It resolve the issues now.
Kindly please review the changes

Thanks

**Comment by crweiner** [comment]
Howdy @ansarisadaffatima! Thank you for adding Taipy to the Hacktoberfest Swag List, and also thank you @vimode  for making sure that their MD formatter was turned off! This project does have some different Markdown requirements, @ansarisadaffatima, and [these Markdownlint rules should be excluded from your linter](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/.mdlrc). One of those flags is that MkDocs requires a 4-space block or a 4-space tab for list intendation, [as mentioned here.](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md#a-to-z-order-of-companies)

I made a few more tweaks and it looks good now, so let's get this merged! Thank you for your help!

thumbs up

**Pull request merged**
