### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by souravroy-test**
adding CAMUNDA in the list

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by souravroy-test** [comment]
Adding CAMUNDA in the swag list

**Comment by crweiner** [comment]
Hi there @souravroy-test! :wave: Thank you so much for contributing to the Hacktoberfest Swag List! I'd love to get CAMUNDA on the List for this year and would apprecaite it if you could tackle a few things:

- Please add a ``` ### C ``` header and add CAMUNDA in the A-Z List of Companies.
- I think it would be great to add a link to the swag signup form in the "How to sign up" section.
- Please make the [Code Climate bot happy](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/253) by working on these few flags.
- Feel free to add your name to the [2020 Contributors list](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md#2020-contributors) within this PR instead of #254. To keep with the Hacktoberfest rules, I don't approve PRs that are just adding a person's name to the contributors list as that artifically inflates their PR count during Hacktoberfest.

Thank you again for your contribution and I hope to hear back soon so we can get this merged and live! :tada: :tada:

**Comment by crweiner** [comment]
Hi again @souravroy-test! :wave: I'd love it if you could please add your name under PR #253 for your work on adding CAMUNDA to the 2020 Hacktoberfest Swag List. During Hacktoberfest, I don't approve PRs that are just "add your name to a list" as that is against the Hacktoberfest rules (and spirit of the holiday). 

So, I will close this PR, but I *do* want your name on the list, just under PR #253, please. :smile: Thank you so much for your contribution!

**Comment by souravroy-test** [comment]
### C header added,
CAMUNDA added in the A-Z List of Companies,
Added InfraCloud in the list.

**Comment by crweiner** [comment]
Woohoo! Thank you @souravroy-test! You rock for adding InfraCloud and CAMUNDA to the Hacktoberfest Swag List! 😃 🎆 I appreciate you taking the time to do so! I've gone ahead and added your name to the Contributor's file as well. 😄 

Have a wonderful Hacktoberfest and I hope to see you again once the holiday starts! 🎃 👍 🎉

**Pull request merged**
