### PR TITLE
Make all off-site links open in a new tab

### LINKED ISSUE #563: Feature: Make all off-site links open in a new tab
MkDocs and the Material theme have support for Python Markdown. To get off-site links to open in a new tab, instead of inline at HacktoberfestSwagList.com, they must be given the `target="_blank"` attribute. 

Please enable the [Attribute Lists](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition) extension so that this can then be added to each off-site link.

[This PR](https://github.com/squidfunk/mkdocs-material/discussions/3660) and [this PR](https://github.com/mkdocs/mkdocs/issues/1958) and [this PR](https://github.com/squidfunk/mkdocs-material/issues/1609) will lead you down the right path. 😄

### PR DESCRIPTION
**Pull request by letsintegreat**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

Closes #563

### CODE REVIEW

**Comment by crweiner** [comment]
Sorry for throwing a monkey wrench in some of your plans here, @letsintegreat. 😅 I've merged some PRs so the list is updated. Would you able to update your fork and/or rebase? I really like how you went through and made sure each link opens in a new tab, which I would like to get merged!

**Comment by letsintegreat** [comment]
@crweiner 
Ah sure, give me some time while I update the fork and make changes!

**Comment by letsintegreat** [comment]
@crweiner There you have it!

**Comment by crweiner** [comment]
Another beautiful job, thank you again @letsintegreat! This was very helpful, now people can stay on the Swag List and still check out the organizations. I appreciate it! 🎉 

great job

**Comment by letsintegreat** [comment]
@crweiner Umm, for some reasons your repository has been excluded from hacktoberfest. I am not sure why.

image

Do you know anything about it?

**Comment by crweiner** [comment]
Thanks for the heads up, I'll reach out to the Hacktoberfest folks to see. 👍

**Comment by letsintegreat** [comment]
@crweiner Alright, looking forward to hearing about any updates.

**Comment by crweiner** [comment]
Hey @letsintegreat  can you please take another look? I reached out to the Hacktoberfest team and they let me know they lifted the exclusion. 😺

**Comment by letsintegreat** [comment]
@crweiner Neat! Excluded status has been removed from your repo. Thanks :D

**Pull request merged**
