### PR TITLE
Aqua added to swag list

### PR DESCRIPTION
**Pull request by deepak2431**

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @deepak2431 , thanks for contributing to the Hacktoberfest Swag List. 

Please be sure you follow the [Contributing guidelines](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) as currently, this PR does not meet them. Also, please take the time to fix the CodeClimate issues as commented by the bot above.

Once that is completed, let me know when you'd like me to take a look again. :+1:

**Comment by deepak2431** [comment]
Hi @crweiner . On which list should I add eligible contribution as mentioned in the blog of Aqua to the merged PR category or to just a PR category?

**Comment by crweiner** [comment]
> Hi @crweiner . On which list should I add eligible contribution as mentioned in the blog of Aqua to the merged PR category or to just a PR category?

That's a great question and I'm not quite sure as the blog post isn't 100% clear. I'd say to stick with the merged category as that's most likely what it is. If you find out differently, feel free to submit a PR changing that. :+1:

**Comment by deepak2431** [comment]
> > Hi @crweiner . On which list should I add eligible contribution as mentioned in the blog of Aqua to the merged PR category or to just a PR category?
> 
> That's a great question and I'm not quite sure as the blog post isn't 100% clear. I'd say to stick with the merged category as that's most likely what it is. If you find out differently, feel free to submit a PR changing that.

Thanks @crweiner

**Comment by deepak2431** [comment]
Hi @crweiner , I think it's all good now. Please review it.
Thanks!

**Comment by crweiner** [comment]
Added in #171, and this contribution will still count towards your Hacktoberfest total. :smile: Thanks again!

**Pull request closed without merging**
