### PR TITLE
Added Akto to the Hacktoberfest Swag List (#737)

### PR DESCRIPTION
**Pull request by biplobsd**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @biplobsd! Could you please adjust the placement of Akto so it is in alphabetical order on the list? Also, please double check the [Contributing Docs](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) and let me know when you're ready for me to take another look.

Thanks!

**Comment by biplobsd** [comment]
Hi @crweiner. I did update the order. Please take a look again.

**Comment by crweiner** [comment]
> I did update the order. Please take a look again.

Perfect, thank you very much @biplobsd! Happy to get this merged, and hope you're having a great Hacktoberfest! 👍 

thank you

**Comment by biplobsd** [comment]
> > I did update the order. Please take a look again.
> 
> Perfect, thank you very much @biplobsd! Happy to get this merged, and hope you're having a great Hacktoberfest! 👍
> 
> thank you [ thank you ](https://camo.githubusercontent.com/141ab5234f02c75f9253c8db761a0e8342e923d36eb8c92e673d36b4711df813/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f33726e5156395749417945627345623174442f67697068792e676966) [ ](https://camo.githubusercontent.com/141ab5234f02c75f9253c8db761a0e8342e923d36eb8c92e673d36b4711df813/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f33726e5156395749417945627345623174442f67697068792e676966)

@crweiner Many thanks to you for creating this amazing repository... 🎉✨

**Comment by biplobsd** [comment]
Recently I hear about @swirl-search from your list. And got a swag. 😀

So Very much Thanks to @crweiner , @vimode

**Comment by biplobsd** [comment]
https://biplobsd.me/blogs/view/contributing-to-open-source-my-hacktoberfest-experience.md

I wrote a blog about my hacktoberfest experience. And I motioned @crweiner and @vimode to my blog 😃

**Comment by crweiner** [comment]
Hey @biplobsd! I'm so happy that this project was a great inspiration for you during Hacktoberfest and connected you to some great companies! That's exactly why I run this List every year; to connect contributors such as yourself with companies they didn't previously know about.. Thanks for the shoutout in your blog and on Twitter too. 😄 

Have a great time contributing to other open source projects during the rest of the year, and I'll see you again for Hacktoberfest 2024!

**Comment by biplobsd** [comment]
@crweiner sure, see you in 2024 if I'm alive 😃. If you feature this type of story, maybe people will be more connected to the companies. Just my thoughts 😀

**Pull request merged**
