### PR TITLE
Added SEF to the hacktoberlist

### LINKED ISSUE #747: Add SEF to Hacktoberfest Swag List
[SEF - Sustainable Education Foundation](https://sef.discourse.group/t/it-s-hacktoberfest-month/543) is giving t-shirts, stickers and exclusive coupons for your contributions to their projects.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

### PR DESCRIPTION
**Pull request by vaibhav-009**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

Fixes #747

### CODE REVIEW

**Comment by vaibhav-009** [comment]
@crweiner please do review this PR.

**Comment by crweiner** [comment]
Cross-posting this from #747:

---

I'm not certain if SEF is offering their own swag for Hacktoberfest, or mentioning that you _could_ win swag in general (they may not be aware that the official event no longer has a shirt and stickers that they send out).

> What is Hacktoberfest?
Hacktoberfest is open to everyone in our global community. Whether you’re a developer, student learning. During the entire month of October, all you have to do is contribute to any open source projects and open at least 4 pull requests. And you can win awesome prizes like a T-shirt, stickers, and coupons.
https://sef.discourse.group/t/it-s-hacktoberfest-month/543

Do you happen to see where they are offering their own swag?

**Comment by crweiner** [comment]
Hi @vaibhav-009!

 I mentioned in #747 that I don't believe SEF is offering their own, unique swag. I appreciate your contribution though, and hope you are having a great Hacktoberfest!

Also, I took a look at the other repos you are contributing to, and be sure to avoid anything that is spam or a simple "+1" to your PR count for Hacktoberfest. Please be sure to [read through the Participation rules](https://hacktoberfest.com/participation/#values) and make sure that each PR you submit is a meaningful contribution that will add value to a project.

Thanks!

**Comment by vaibhav-009** [comment]
hey @crweiner I have made a PR now for another issue can you please review that ? 
#774

**Pull request closed without merging**
