### PR TITLE
Added Hasura to the list

### PR DESCRIPTION
**Pull request by itsBaivab**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hi @itsBaivab! Can you please[ fix the trailing spaces that CodeClimate has flagged?](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/764) Thank you!

**Comment by vimode** [comment]
Hey @itsBaivab Hasura has [posted a new blog post](https://hasura.io/blog/the-hasura-hacktoberfest-fiesta-build-a-supergraph-and-win-1000/) providing more information about the prizes, event, contributions. 

Can you please update all the information based on that blog post?

Thank you.

**Comment by itsBaivab** [comment]
Fixed everything and updated Hasura

**Comment by crweiner** [comment]
Hello @itsBaivab and @SparklinStar! Thank you for adding Hasura to the Hacktoberfest Swag List! I'm very happy to see them returning to Hacktoberfest for another year, and thank you for making some tweaks to your listing.

I've gone ahead and made further changes, as Hasura is offering a t-shirt + sticker pack swag as well for contributing to the Hasura docs ([particularly these issues tagged for Hacktoberfest](https://github.com/hasura/graphql-engine/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest+)), [as mentioned in their blog post](https://hasura.io/blog/the-hasura-hacktoberfest-fiesta-build-a-supergraph-and-win-1000/). I really wanted to get them up on the list, so I made these edits myself. 😄 

Thank you again for your contribution, and have a great Hacktoberfest! 🥳 

hat tip

**Pull request merged**
