### PR TITLE
Added Nuceli to swagger list.

### PR DESCRIPTION
**Pull request by githubashutoshsoni**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by vimode** [comment]
Hey @githubashutoshsoni there is an update to the rewards and a new leaderboard for the same! 
https://blog.projectdiscovery.io/announcing-the-nuclei-templates-community-leaderboard-and-rewards/

As you fix the code climate errors, can you please update it with the necessary information and the link too to your PR? Thank you

**Comment by githubashutoshsoni** [comment]
Hey sorry, I'll be travelling and won't be available. please close this PR if it's not helpful. thanks

**Comment by crweiner** [comment]
Hi @githubashutoshsoni! Thank you for your PR! Can you please point out where they list their participating in Hacktoberfest and say where they offer the stickers?

**Comment by githubashutoshsoni** [comment]
@crweiner here in this link: https://blog.projectdiscovery.io/announcing-the-nuclei-templates-community-leaderboard-and-rewards/


What additional rewards are available besides bounties?

In addition to bounties, we also reward contributors with:

• Swag such as t-shirts and stickers.

• Invites to security conferences for standout contributors.

• Stickers for all first-time contributors, regardless of the bounty.

Contributors who feel their pull request or issue was overlooked for first-time contributor stickers can reach out on our Discord: [ProjectDiscovery Discord](https://discord.com/invite/projectdiscovery?ref=blog.projectdiscovery.io).

**Comment by vimode** [comment]
This PR can be closed. 
This has been added to the list in the merged PR #969 under the company name `Project Discovery`

Thank you for all the info @githubashutoshsoni

**Pull request closed without merging**
