### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sameshl**
small typo fix :sweat_smile:

`mentionned` -> `mentioned`

### CODE REVIEW

**Comment by crweiner** [comment]
Thank you for spotting that, and it has been fixed in PR #89 :+1:

**Comment by sameshl** [comment]
@crweiner Oh didn't check that. My bad. :+1:

**Comment by crweiner** [comment]
No worries! We're all good! Your contribution will still count towards the official Hacktoberfest swag. :-)

**Comment by sameshl** [comment]
Thanks, @crweiner. Appreciate it! :smiley:

**Pull request closed without merging**
