### PR TITLE
Add Les-Tilleuls.coop to companies who contribute to Hacktoberfest.

### PR DESCRIPTION
**Pull request by Taminoful**
Les-Tilleuls.coop is the company behind [API Platform](https://api-platform.com/), they announced they'd give away swag to anyone who contributes at least four PRs to their repositories.

### CODE REVIEW

**Comment by crweiner** [comment]
Wow!! Thank you @Taminoful for finding a new company and adding them to the Hacktoberfest Swag List!! I've never heard of API Platform before and I hope that we can help bring lots of meaningful PRs their way.

Do you happen to know if there is any sort of signup form that people will have to submit? Also, [Kevin's personal blog(way at the bottom of this post)](https://dunglas.fr/2019/09/api-platform-2-5-revamped-admin-new-api-testing-tool-next-js-and-quasar-app-generators-patch-and-json-schema-support-improved-openapi-and-graphql-support/) says that it requires 3 PRs, while his Tweet does say 4.

Once you or I are able to clarify what exactly the requirements are, then we can add them to the list!

Thanks again for your hard work and I hope we can get this merged soon! :+1:

**Comment by crweiner** [comment]
Update, it appears to be [only 3 PRs](https://twitter.com/dunglas/status/1179041442976731137?s=19), so if you could please update this I'll get it merged ASAP!

**Comment by Taminoful** [comment]
Hey @crweiner,

glad you like my contribution to your project. Thank you for your research! I just updated the README.md file according to the new information. Sadly there's no information about any sign ups available yet, if I hear something about it I'll add it to this repository asap.

**Comment by crweiner** [comment]
Marvelous job @Taminoful!! Thank you so much for your help adding the API Platform and Les-Tilleuls.coop to the Hacktoberfest Swag List!!

great job

Have a marvelous Hacktoberfest and have fun contributing to cool open-source projects and earning swag! :+1:

**Pull request merged**
