### PR TITLE
Add IBM to list

### PR DESCRIPTION
**Pull request by thehungrycoder**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

### CODE REVIEW

**Comment by crweiner** [comment]
Hey @thehungrycoder! 👋  I think that IBM offering swag to their employees is really freaking cool! 🤯 

Do you have any way I can verify this listing, PR requirements, swag, etc? Is there anything public-facing that I can see to double check that this is correct? Thank you! 👍

**Comment by thehungrycoder** [comment]
Hi, didn't notice anything public. If you want, you can wait until another IBM employee verifies it!

**Comment by crweiner** [comment]
Do you happen to know anyone else who works at IBM and makes public commits to an [IBM repo](https://github.com/IBM)? Basically, [if anyone from here](https://github.com/orgs/IBM/people) wishes to confirm this then that's good enough for me!

**Comment by thehungrycoder** [comment]
> Do you happen to know anyone else who works at IBM and makes public commits to an [IBM repo](https://github.com/IBM)? Basically, [if anyone from here](https://github.com/orgs/IBM/people) wishes to confirm this then that's good enough for me!

unfortunately no. but i expected to be in that list in 24hrs

**Comment by crweiner** [comment]
Sweet, @thehungrycoder! LGTM! I think it's really cool that IBM is doing something for their employees during Hacktoberfest. I know that this clearly doesn't impact the vast majority of people browsing the repo, but I stil think that it's really cool and something IBM should be proud of :smile:

Thank you for your contribution and happy Hacktoberfest! :tada:

**Pull request merged**
