### PR TITLE
Add Hasura Project to the list

### PR DESCRIPTION
**Pull request by cendekia**

### CODE REVIEW

**Comment by crweiner** [comment]
Hay there @cendekia!

Thank you so much for taking the time to add Hasura to the Hacktoberfest Swag List as well as fix those CodeClimate/mdl flags! 

Would you mind please fixing these merge conflicts so we can get them added to the list?

I've gone ahead and updated the title of this PR to better reflect that it doesn't just include adding you to the Contributors list but also to add Hasura.

Also, I'll be closing the other PRs as this latest one makes the others invalid. That way, we can keep your contribution nice and neatly in one PR and it's fairer to everyone else. :+1: 

Once you've got those conflicts resolved, we can get this merged! Thanks!

**Comment by cendekia** [comment]
@crweiner Ok it's ready and thank you for the help

**Comment by crweiner** [comment]
Thank you for all of your hard work on this PR!!! Everything looks good at first glance (besides the new merge conflict I created from a different PR...sorry)! I'll fix the merge conflict in the morning or you're free to do it too if you wish.

thumbs up

Looking forward to getting this merged and I greatly appreciate your time and assistance making this little project the best it can be!

**Comment by crweiner** [comment]
Sweet, thanks for fixing the merge conflict. Let's get this puppy live! Thanks again!!!

**Pull request merged**
