### PR TITLE
Added Hasura Project

### PR DESCRIPTION
**Pull request by cendekia**

### CODE REVIEW

**Comment by cendekia** [comment]
This PR is for https://github.com/crweiner/hacktoberfest-swag-list/issues/57

**Comment by crweiner** [comment]
Hi @cendekia!! Thanks for your hard work in writing up Hasura for the Hacktoberfest Swag List!

Can you please go through the [issues flagged by CodeClimate](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/63) and take care of them, please? They're very minor, but it helps to make sure that the list builds properly with each new contribution. You can see a (nearly) live update of your changes [by clicking here](https://deploy-preview-63--hacktoberfest-swag-list.netlify.com/)

Once you tackle that, I'll get this merged and live!!! Thank you! :smiley_cat: :+1:

**Comment by cendekia** [comment]
https://github.com/cendekia/hacktoberfest-swag-list/commit/3ba7f6a73d72a6d14adc6dcdbe9f6613bb2ac506

All good now @crweiner

**Comment by crweiner** [comment]
Being worked on in #69

**Pull request closed without merging**
