### PR TITLE
Added Quine to the list

### LINKED ISSUE #825: Add Quine to Hacktoberfest Swag List
[Quine](https://twitter.com/quine_sh/status/1712081594431782973) is participating in the Hacktoberfest 2023!

No information about the swag or any participation details have been provided yet. 
But they their own [leaderboard](https://docs.quine.sh/misc/hacktoberfest) with some information about it.

Once more information is provided, this could be added to the list.

This issue is open for anyone who wants to contribute to this repo.

Please read the [contributing guideline](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) to understand the formatting and the information expected from the announcement for your PR to be successfully merged.

Please check the [active PRs](https://github.com/crweiner/hacktoberfest-swag-list/pulls) to make sure there isn't already an active PR for this issue.

### PR DESCRIPTION
**Pull request by bharatr21**
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Closes #825 
Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

Keeping it in draft since Quine said they will be adding more details in [this Twitter Thread](https://twitter.com/quine_sh/status/1712081594431782973)

### CODE REVIEW

**Comment by vimode** [comment]
I think with the latest tweet(which you already added) it has enough details to be added to the list.  Go ahead fix those errors and make this a PR.

**Comment by bharatr21** [comment]
@vimode I think it's ready for review now

**Review by vimode — CHANGES_REQUESTED** [review]
This should simply it a bit more, don't you think? 
If these edits cause any code climate errors, please fix those. 
Thank you.

**Comment by bharatr21** [comment]
Applied the suggestions and fixed whitespace/code climate issues, 
@vimode please re-review

**Comment by crweiner** [comment]
Thank you very much @vimode and @bharatr21 for working together to add Quine to the Hacktoberfest Swag List for 2023! Let's get them up there!

clapping

**Pull request merged**
